### ISSUE TITLE
Inconsistencies with "conservative" power 

### ISSUE THREAD

**Issue by matthewravery** [tylermorganwall/skpr#42]
For multi-level categorical factors, the `conservative = TRUE` option in `eval_design` generates incorrect values. The script below demonstrates this for single-factor designs with four and five levels. Errors are on the order of 30 or 40 percentage points. I haven't looked at more complicated designs (e.g., multi-factor, interaction effects, etc.), but this issue could be present for those, too. 

```
set.seed(20180416)
library(tidyverse)
nsamp <- 10:30
nlevels <- 3:5

make_grid_catagorical_uni <- function(n, nlev){
  
  canset <- tibble(x = factor(seq(-1, 1, length.out = nlev)))
  skpr::gen_design(canset, ~ x, trials = n) %>% 
    as_tibble() 
  
}

out <- NULL
for(nn in nsamp){
  for(nlev in nlevels){
    out <- out %>% 
      bind_rows(
        
        make_grid_catagorical_uni(nn, nlev) %>% 
          skpr::eval_design(~., .05, conservative = T) %>% 
          filter(parameter == "x", type == "effect.power") %>% 
          mutate(nlev = nlev, n = nn)
      ) 
    
  }
}

out %>% 
  ggplot(aes(x = n, y = power)) +
  geom_point(size = 2) + geom_line() +
  facet_grid(~ nlev) +
  scale_y_continuous(breaks = seq(0, 1, by = .2)) +
  scale_x_continuous(breaks = seq(10, 30, by = 5), minor_breaks = NULL) +
  coord_cartesian(ylim = c(0, 1)) +
  ggtitle("Conservative power from skpr by sample size and number of levels")


###
#Same sample size, generating multiple designs
out <- NULL
for(nn in 1:50){
  for(nlev in nlevels){
    out <- out %>% 
      bind_rows(
        
        make_grid_catagorical_uni(19, nlev) %>% 
          skpr::eval_design(~., .05, conservative = T) %>% 
          filter(parameter == "x", type == "effect.power") %>% 
          mutate(nlev = nlev, iteration = nn)
      ) 
    
  }
}

out %>% 
  ggplot(aes(x = iteration, y = power)) +
  geom_point(size = 2) + geom_line() +
  facet_grid(~ nlev) +
  scale_y_continuous(breaks = seq(0, 1, by = .2)) +
  scale_x_continuous(breaks = seq(1, 50, by = 10), minor_breaks = NULL) +
  coord_cartesian(ylim = c(0, 1)) +
  ggtitle("Conservative power from skpr with multiple designs (n = 19)")
```

**Comment by tylermorganwall** [comment]
Hi Matt,
I just pushed a fix for this: `v0.47.4`. 
Best regards,
Tyler

**Comment by matthewravery** [comment]
Updating fixed the most egregious variation, but power estimates still appear to be stochastic in some cases. 

Run the second part of the above script. Power for these designs should be deterministic, but when you generate multiple designs, the power estimates fluctuate by 5 to 10 percentage points. 

Take the design with a  single four-level factor and 19 runs. The optimal design here will have five observations for three levels and four observations for a fourth level. `skpr` is reporting power estimates of either 58 or 64 percent. The correct number is 58, which is your power when you set the coefficients for two of the 5-observation factor levels equal to zero. 64 is what you get when you set the coefficient for the 4-observation factor level and one of the 5-observation factor levels to zero instead.

**Comment by tylermorganwall** [comment]
The power estimates are not stochastic in eval_design--the varying power numbers are due to differences in the design unrelated to its optimality. For unbalanced designs, the order in which the levels are coded can affect the resulting power values. I have implemented a change in the latest version, `v0.48.2`, that will consistently pick out the more conservative ordering.
